query Category($id:ID!, $date:DateTime){  
  category(id: $id) {
    id
    title
    demands(sort:"expirationDate:desc", where:{state:0, expirationDate_gt:$date }){
      id
      title
      description
      expirationDate
      state
      user{
        id
        lastname
        firstname
      	username
      }
    }
    offers(sort:"expirationDate:desc", where:{state:0}){
      id
      title
      description
      expirationDate
      state
      user{
        id
      	username
        lastname
        firstname
      }
    }
  }
}