query Categories {  
  categories(sort:"title:asc") {
    id
    title
    demands(sort:"expirationDate:desc"){
      id
      title
      description
      expirationDate
      user{
        id
      	username
      }
    }
    offers(sort:"expirationDate:desc"){
      id
      title
      description
      expirationDate
      user{
        id
      	username
      }
    }
  }
  }
