query Category($id:ID!){  
  category(id: $id) {
    id
    title
    demands(sort:"expirationDate:desc"){
      id
      title
      description
      expirationDate
      member{
        id
      	pseudo
      }
    }
    offers(sort:"expirationDate:desc"){
      id
      title
      description
      expirationDate
      member{
        id
      	pseudo
      }
    }
  }
}