query Member($id:ID!){
  member(id:$id){
    id
    lastname
    firstname
    pseudo
    birthday
    phonenumber
    email
    address
    town
    zip
    password
    walletAmount
    registrationDate
    
    demands{
      id
      title
      description
      expirationDate
      category{
        id
        title
      }
    }
    offers{
      id
      title
      description
      expirationDate
      category{
        id
        title
      }
    }
  }
}