query OffersWithMember {  
  offers(sort:"expirationDate:asc") {
    id
    title
    description
    expirationDate
    member{
      id
      pseudo
    }
    category{
      id
      title
    }
  }
}