query Offer($id:ID!) {  
  offer(id:$id){
    id
    title
    description
    offerDate
    expirationDate
    amount
    state
    member{
      id
      pseudo
      walletAmount
    }
    category{
      id
      title
    }
    memberExchange{
        id
        pseudo
        walletAmount
    }
  }
}