query Offer($id:ID!) {  
  offer(id:$id){
    id
    title
    description
    offerDate
    expirationDate
    amount
    state
    user{
      id
      firstname
      lastname
      username
      walletAmount
    }
    category{
      id
      title
    }
    userExchange{
        id
        firstname
        lastname
        username
        walletAmount
    }
  }
}