query OffersWithUser {  
  offers(sort:"expirationDate:asc", where:{state:0, expirationDate_gt:$date}) {
    id
    title
    description
    expirationDate
    user{
      id
      username
      lastname
      firstname
    }
    category{
      id
      title
    }
  }
}