query Demands($user:ID, $date:DateTime){
  demands(where:{user:$user, expirationDate_lt:$date, state:0}, limit:20, sort:"expirationDate:asc"){
    id
    title
    description
    expirationDate
    user{
      id
      username
    }
    amount
    userExchange{
      id
    	username
    }
  }
}
