query DemandsWithMember {  
  demands(sort:"expirationDate:asc") {
    id
    title
    description
    demandDate
    expirationDate
    member{
      id
      pseudo
    }
    category{
      id
      title
    }
  }
}