query DemandsWithMember {  
  demands(sort:"demand_expiration_date:asc") {
    id
    demand_title
    demand_description
    demand_date
    demand_expiration_date
    member{
      id
      pseudo
    }
    category{
      id
      title
    }
  }
}