query Demands {  
  demands(sort:"expirationDate:desc") {
    id
    title
    description
    demandDate
    expirationDate
    amount
    state
    user{
      id
      username
    }
    userExchange{
      id
      username
    }
  }
}