query Demand($id:ID!) {  
  demand(id:$id){
    id
    title
    description
    demandDate
    expirationDate
    amount
    state
    user{
      id
      lastname
      firstname
      username
      walletAmount
    }
    category{
      id
      title
    }
    userExchange{
        id
        lastname
        firstname
        username
        walletAmount
    }
  }
}