query Demands{
  demands{
    id
    title
    description
    state
    user{
      id
      username
      lastname
      firstname
    }
    amount
    userExchange{
      id
      username
      lastname
      firstname
    }
  }
}
