query Demands {  
  demands(sort:"expirationDate:desc") {
    id
    title
    description
    demandDate
    expirationDate
    amount
    state
    member{
      id
      pseudo
    }
    memberExchange{
      id
      pseudo
    }
  }
}