query DemandsWithUser($date:DateTime) {  
  demands(sort:"expirationDate:asc", where:{state:0, expirationDate_gte:$date}) {
    id
    title
    description
    demandDate
    expirationDate
    user{
      id
      username
      lastname
      firstname
    }
    category{
      id
      title
    }
  }
}