query UserWithExpiration($id:ID!, $date:DateTime){
  user(id:$id){
    id
    lastname
    firstname
    username
    birthday
    phonenumber
    email
    address
    town
    zip
    walletAmount
    registrationDate
    token{
        id
        token
    }
    
    demands(where:{expirationDate_lt:$date}, limit:20, sort:"expirationDate:asc"){
      id
      title
      description
      expirationDate
      amount
      state
      userExchange{
        id
      	username
        lastname
        firstname
      }
      category{
        id
        title
      }
    }
    offers(where:{expirationDate_lt:$date}, limit:20, sort:"expirationDate:asc"){
      id
      title
      description
      expirationDate
      amount
      state
      userExchange{
        id
      	username
        lastname
        firstname
      }
      category{
        id
        title
      }
    }
  }
}
      